export const providers = [
  "AAR Insurance Company Limited",
  "Africa Merchant Assurance Company Limited",
  "AIG Kenya Insurance Company Limited",
  "Allianz Insurance Company of Kenya Limited",
  "APA Insurance Limited",
  "APA Life Assurance Company Limited",
  "Britam General Insurance Company (K) Limited",
  "Cannon Assurance Company Limited",
  "Capex Life Asssurance Company Limited",
  "CIC General Insurance Company Limited",
  "Continental Reinsurance Limited (Kenya)",
  "Corporate Insurance Company Limited",
  "Directline Assurance Company Limited",
  "East Africa Reinsurance Company Limited",
  "Fidelity Shield Insurance Company Limited",
  "First Assurance Company Limited",
  "GA Insurance Limited",
  "Geminia Insurance Co. Limited",
  "ICEA Lion General Insurance Company Limited",
  "Intra Africa Assurance Company Limited",
  "Invesco Assurance Company Limited",
  "Kenindia Assurance Company Limited",
  "Kenya Orient Insurance Limited",
  "Kenya Reinsurance Corporation Limited",
  "Madison Insurance Company Kenya Limited",
  "Mayfair Insurance Company Limited",
  "Occidental Insurance Company Limited",
  "Old Mutual Assurance Company Limited",
  "Pacis Insurance Company Limited",
  "Phoenix of East Africa Assurance Co. Limited",
  "Pioneer General Insurance Company Limited",
  "Pioneer Assurance Company Limited",
  "Prudential Life Assurance Company Limited",
  "Resolution Insurance Company Limited",
  "Saham Assurance Company Kenya Limited",
  "Sanlam General Insurance Company Limited",
  "Takaful Insurance of Africa Limited",
  "Tausi Assurance Company Limited",
  "The Heritage Insurance Company Limited",
  "The Jubilee Insurance Company of Kenya Limited",
  "The Kenyan Alliance Insurance Company Limited",
  "The Monarch Insurance Company Limited",
  "Trident Insurance Company Limited",
  "UAP Insurance Company Limited",
  "Xplico Insurance Company Limited",
  "Other",
];
